Adding new project
developer-edwin/portfolio pull request #1
Opened 2022-05-26 01:48 UTC by developer-edwin

## Creating a first project 

> Creating a copy from figma

Practicing:
- Flexbox
- CSS
- HTML

2022-05-26 02:42 UTC, aimemalaika requested changes
Hi @developer-edwin, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️

- [x] Kindly make sure that the logo is a link
- [x] Kindly put the hamburger button inside  a nav tag
- [ ] Kindly use the font used in the Figma design
- [ ] The first text should be in an `h1`tag as it is the proper semantic tan requested in the requirement
- [ ] The second text should be in a `p` tag as it is the proper semantic tag of  a paragraph
- [ ] The social media icons should be in a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag) and is aligned using flexbox
- [ ] Kindly push sufficient changes to this pull request that will facilitate the review

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 18:23 UTC, jaflih requested changes
Hi @developer-edwin , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>


 ## Highlights

All linters are passing ✔️
Good commit history ✔️
Good PR description ✔️

 ## Required Changes ♻️

_Check the comments under the review._

Great job I can see you improve your design by following the requirement of the previous review 👍 
Please stick to the Figma design, and you'll be approved.

Your design: 
<img width="449" alt="image" src="https://user-images.githubusercontent.com/7243132/170551305-5007fa02-d45a-44ca-b378-a1d8c8cd0e31.png">


Figma:
<img width="288" alt="image" src="https://user-images.githubusercontent.com/7243132/170551379-48113b48-e3de-4a4c-a13a-5df50228897d.png">


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 18:23 UTC, jaflih commented on style.css
> +}
Please, use good color to stick Figma design.
The good color here is #344563

Your design:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/7243132/170547870-91cb4b2d-a2e1-49f2-866d-15c90e09029b.png">

Figma:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/7243132/170547958-04357f63-a442-43b3-bf8e-b2f87f9ec864.png">

2022-05-26 18:23 UTC, jaflih commented on style.css
>  }
Kindly make sure each icon has the same spacing as in Figma.

Your design:
<img width="157" alt="image" src="https://user-images.githubusercontent.com/7243132/170548246-d51978fc-1cf1-4027-830b-90b9c888b5bf.png">

Figma
<img width="219" alt="image" src="https://user-images.githubusercontent.com/7243132/170548716-b06813bb-e2e0-4aad-b101-60ce1f349a78.png">

2022-05-26 18:23 UTC, jaflih commented on style.css
> +}
Good job using `background`! 
Unfortunately, as you see in the following screenshot, the image doesn't cover all the section. To correct it, you can use `background-size: cover` 

<img width="448" alt="image" src="https://user-images.githubusercontent.com/7243132/170550275-a539044e-56ad-4ed2-b034-6d0b678cc079.png">

2022-05-26 18:23 UTC, jaflih commented on style.css
> +body {
Please create a section for this background image, as you see in Figma, this image is only for the 1st section.
<img width="196" alt="image" src="https://user-images.githubusercontent.com/7243132/170550599-23a899c7-cae9-4b5c-acec-931ab6c69a6e.png">

2022-05-26 21:51 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @developer-edwin 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Require Changes :recycle::recycle: 
- [ ] **Check the comments under the review**.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 21:51 UTC, tresorsawasawa commented on style.css
> +}
- [ **OPTIONAL** ] Kindly make sure **spacing at the top**  is the same use used on the Figma design.
### Figma design
![mtf](https://user-images.githubusercontent.com/83042742/170579662-2ff173a3-bccc-4902-a2f8-e26c77407a35.png) 

 ### Your design 
![mtop](https://user-images.githubusercontent.com/83042742/170579733-c38aa30b-9141-4233-ae1c-f27052c137e8.png) |

2022-05-26 21:51 UTC, tresorsawasawa commented on style.css
>  }
- [ **OPTIONAL** ] Kindly make sure **spacing at the bottom**  is the same used on the Figma design.
### Figma design
![mtb](https://user-images.githubusercontent.com/83042742/170580690-fa0214e7-e0a0-4bb3-9e02-12d202ead3ed.png)

 ### Your design 
![smbt](https://user-images.githubusercontent.com/83042742/170580625-c2e19ea2-9a6b-4f25-adf9-74beb75858dc.png)

2022-05-26 21:51 UTC, tresorsawasawa commented on style.css
>  }
- [ **OPTIONAL** ] Kindly make sure in your that the **the spacing from bottom** matches perfectly the one from [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)
### Figma Design
![mtb](https://user-images.githubusercontent.com/83042742/170582291-6ebd169b-b314-4a40-bb54-5305b85803ef.png)
### Your Design
![smbt](https://user-images.githubusercontent.com/83042742/170582204-76219610-1699-4d1b-bd34-0c22b8501522.png)

2022-05-26 21:51 UTC, tresorsawasawa commented on index.html
> +            </ul>
- [ ] Good job so far by adding some of the changes required by previous reviewers. So, I noticed that they required you to wrap each social icon in a `<a>` tag. As I can see it is not fixed. Your code should look like this:
````bash
      <ul>
            <li>
                <a href="#"><img src="./" alt=""></a>
            </li>
            <li>
                <a href="#"><img src="./" alt=""></a>
            </li>
           .....
        </ul>
````

2022-05-26 21:51 UTC, tresorsawasawa commented on style.css
>  }
- [ ] Good job so far by again adding some of the changes required by previous reviewers. So, I noticed again that you didn't match the color of your logo with the one from Figma. This is because you style it in the wrong place. Here is where you should put your code:
 ```bash
.logo a {
  ......
  color: #6070ff;
}
```
| Figma logo | You logo |
| --------------- | ------------|
| ![lo](https://user-images.githubusercontent.com/83042742/170583900-afbf1cb9-0727-4837-8bd9-669c565bc56e.png) | ![log](https://user-images.githubusercontent.com/83042742/170583940-7bc1a477-97f8-40fd-851a-060afb1d5079.png) |

2022-05-26 21:51 UTC, tresorsawasawa commented on style.css
> +
- [ **OPTIONAL** ] Kindly make sure that the **the spacing from the top to the sectionOne** matches perfectly the one from [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)
### Figma Design
![mtf](https://user-images.githubusercontent.com/83042742/170584238-4f47babd-4cd5-4ed0-988c-70594515e6ff.png)

### Your Design
![mtop](https://user-images.githubusercontent.com/83042742/170584292-62932f54-7218-4c54-9d7f-d6698f96a31e.png)

2022-05-26 21:51 UTC, tresorsawasawa commented on style.css
>  }
- [ **OPTIONAL** ] Kindly make sure that the **the spacing between paragraph and LET'S CONN..** and **between icons** matches perfectly the one from [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)
### Figma Design
![ftxtb](https://user-images.githubusercontent.com/83042742/170584986-8c68f0f0-3b8f-4af4-80e5-efb419f58d88.png)

### Your Design
![stextb](https://user-images.githubusercontent.com/83042742/170584785-00c8b402-f0d9-463f-b096-f56b0a398163.png)

2022-05-26 21:51 UTC, tresorsawasawa commented on style.css
>  }
- [ **OPTIONAL** ] Kindly make sure that the **the spacing between paragraph and LET'S CONN..** and **between icons** matches perfectly the one from [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)
### Figma Design
![ftxtt](https://user-images.githubusercontent.com/83042742/170585688-5b8067c5-3be0-4464-b0d7-1d382835a028.png)

### Your Design
![stxttop](https://user-images.githubusercontent.com/83042742/170585641-288041ca-1e23-426d-99ac-0acd97b341d2.png)

2022-05-28 03:34 UTC, Ismailco approved these changes
### Hi @developer-edwin,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 03:34 UTC, Ismailco commented on index.html
> +            <div class="footer-title">LET'S CONNECT</div>
- [ ] [OPTIONAL] This suppose to be a link to an external site or to an email, please consider using a ```<a>``` tag inside it, so it redirects the user to the proper site of the call to action

2022-05-28 03:34 UTC, Ismailco commented on style.css
> +section.sectionOne {
- [ ] [OPTIONAL] You can use flexbox to align the whole section instead of just some elements, please consider using flexbox for this section e.g. 
```
section.sectionOne {
  background: url(images/background.png) no-repeat;
  background-size: 100%;
  height: 100vh;
  display: flex;
  flex-direction: column;
  /* justify-content: space-around; */
}
```

2022-05-28 05:36 UTC, merged