Adding working cards and about section
developer-edwin/portfolio pull request #2
Opened 2022-05-28 08:45 UTC by developer-edwin

## Adding new areas
- Working cards
- About section

2022-05-28 09:54 UTC, KayLemba requested changes
Hi @developer-edwin   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
- Please add information about your project to your README file. Here is an example of how your read me file should look like [here](https://github.com/KayLemba/KaloloPortfolio/blob/master/README.md) your README doesnt contain any infomation about please implement this for it is an important project requirement.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-28 09:54 UTC, KayLemba commented on index.html
> +            <span class="card_button">See Project</span>
Kindly add borders around your cards and also add a border-radius -left on the introduction section and a border-radius-right on your about section. 
This is how you design looks:
![akak](https://user-images.githubusercontent.com/79506105/170819614-dc58adb8-9d11-41cc-b002-45d0e943153d.png)

This is an example of how your portfolio should look like:
![Kalolo's Portfolio - kalololembasportfolio netlify app](https://user-images.githubusercontent.com/79506105/170819762-7218e369-de1c-41f5-ac8e-aa95b19e5bf9.png)

Please its important to pay attention to detail to avoid mistakes please carefully inspect the template on figma [here](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)

Please dont add the contact form.

2022-05-28 09:54 UTC, KayLemba commented on index.html
> +    </section>
Please add the correct colors for the see project button carefully inspect it on figma and add the correct properties for the button. 

This is how you button looks: 
![Screenshot from 2022-05-28 13-06-14](https://user-images.githubusercontent.com/79506105/170819976-e44349dd-102e-4f4d-a650-425bdf7ab651.png)

Follow this design on figma:
![Screenshot from 2022-05-28 13-44-41](https://user-images.githubusercontent.com/79506105/170820066-614ab861-ff29-4f4d-b8fc-a33e1e430c0b.png)

Your see project button must also have a hover effect please look at the image below of how your button should behave when its hovered upon and when its pressed  implement this for it is an important project requirement.

![Screenshot from 2022-05-28 13-45-46](https://user-images.githubusercontent.com/79506105/170820140-5969fc4e-b400-4061-a57a-4692619807a0.png)

2022-06-03 20:09 UTC, vechicin requested changes
# Hi @developer-edwin  ✋, 

Good job so far! 🔥 
You still need to work on some issues to go to the next project, but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good PR title/description
- [x] Organized code

## Required Changes ♻️

- [ ] You should change your branch name, `first-commit` to something more descriptive of what is implemented in this branch. Kindly fix this as it is a [general requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#general-requirements).

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 20:09 UTC, vechicin commented on index.html
> +        </div>
According to the project requirements, the categories should be wrapped in a `<ul>` and each category should be wrapped in a `<li>`. The same is true for the list of languages (JavaScript, HTML, CSS).

<img width="747" alt="Screen Shot 2022-06-03 at 15 00 52" src="https://user-images.githubusercontent.com/82426682/171941840-a970678a-a0ec-4363-a945-ddcc6d8a389c.png">

Kindly fix this.

2022-06-03 20:09 UTC, vechicin commented on style.css
> +}
According to the project requirements, this entire section should be aligned with flexbox.

<img width="236" alt="Screen Shot 2022-06-03 at 15 02 37" src="https://user-images.githubusercontent.com/82426682/171942188-5ee4fa2c-b656-4043-94ab-cafcaefcff67.png">

Kindly fix this.

Additionally, this section doesn't quite look like the one from the template design.

Here's your design:

<img width="244" alt="Screen Shot 2022-06-03 at 15 04 38" src="https://user-images.githubusercontent.com/82426682/171942600-ada50950-9e02-4b34-b9fa-e6da6158f313.png">

<img width="245" alt="Screen Shot 2022-06-03 at 15 04 57" src="https://user-images.githubusercontent.com/82426682/171942651-a6df995a-c079-40a1-986c-6dd3ac01a485.png">

Here's the template design:

<img width="174" alt="Screen Shot 2022-06-03 at 15 05 21" src="https://user-images.githubusercontent.com/82426682/171942721-11cab0de-e5c2-4e34-bc88-68884a33934a.png">

You should fix margins/paddings amongst other teams to better match the template design as it is a project requirement.

<img width="559" alt="Screen Shot 2022-06-03 at 15 06 18" src="https://user-images.githubusercontent.com/82426682/171942854-c6937355-2463-4741-bf02-9ca0060201b0.png">

Kindly fix this.

2022-06-03 23:07 UTC, algerina approved these changes
Hi @developer-edwin , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/FbZYCW78PANyM/giphy.gif"/>

## Highlights
- Your and commits are meaningful.
- Linters are passing.
- You implemented the requested changes by the previews TSE.
## Optional suggestions:
Please check the comments below

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 23:07 UTC, algerina commented on style.css
> +}
- [ Optional] In order to improve this section please add a` margin-bottom`.

2022-06-03 23:07 UTC, algerina commented on index.html
> +                    <div class="text">Lenguajes</div>
- [ Optional] Kindly replace the word `Lenguajes` with `Languages`.

2022-06-03 23:30 UTC, merged